"""init 2

Revision ID: 1f45b624c01b
Revises: abf341f0e082
Create Date: 2021-09-02 23:55:57.851680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f45b624c01b'
down_revision = 'abf341f0e082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abonents',
    sa.Column('abonent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('abonent_id')
    )
    op.create_table('emails',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('abonent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abonent_id'], ['abonents.abonent_id'], ),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.create_table('notes',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('date_note', sa.DateTime(), nullable=True),
    sa.Column('abonent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abonent_id'], ['abonents.abonent_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_table('phones',
    sa.Column('phone_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('abonent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abonent_id'], ['abonents.abonent_id'], ),
    sa.PrimaryKeyConstraint('phone_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phones')
    op.drop_table('notes')
    op.drop_table('emails')
    op.drop_table('abonents')
    # ### end Alembic commands ###
