"""init 5

Revision ID: 3fb622460baf
Revises: a8cbe474a301
Create Date: 2021-09-10 11:43:19.685170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fb622460baf'
down_revision = 'a8cbe474a301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    op.drop_table('emails')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('email_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('abonent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['abonent_id'], ['abonents.abonent_id'], name='emails_abonent_id_fkey'),
    sa.PrimaryKeyConstraint('email_id', name='emails_pkey')
    )
    op.create_table('notes',
    sa.Column('note_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('note', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('date_note', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('abonent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['abonent_id'], ['abonents.abonent_id'], name='notes_abonent_id_fkey'),
    sa.PrimaryKeyConstraint('note_id', name='notes_pkey')
    )
    # ### end Alembic commands ###
