"""init 3

Revision ID: ed0ac0f7cb92
Revises: 1f45b624c01b
Create Date: 2021-09-05 18:03:17.151797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0ac0f7cb92'
down_revision = '1f45b624c01b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
