"""init 4

Revision ID: eecb1f2056a8
Revises: ed0ac0f7cb92
Create Date: 2021-09-05 19:34:59.406935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eecb1f2056a8'
down_revision = 'ed0ac0f7cb92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
